# Generated by Django 4.2.13 on 2024-06-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docx_file',
            fields=[
                ('sr', models.IntegerField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='docx_files')),
                ('session_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('p_input', models.CharField(max_length=255)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
