# Generated by Django 4.2.13 on 2024-06-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docx_file',
            name='sr',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
